SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;


CREATE TABLE IF NOT EXISTS ctc_applications (
aid int(10) NOT NULL,
  email varchar(64) NOT NULL,
  course int(10) NOT NULL,
  comments varchar(1024) NOT NULL,
  submitdate varchar(10) NOT NULL,
  tutored int(1) NOT NULL,
  `name` varchar(64) NOT NULL
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=2 ;

CREATE TABLE IF NOT EXISTS ctc_courses (
cid int(10) NOT NULL,
  `code` varchar(16) NOT NULL
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=4 ;

CREATE TABLE IF NOT EXISTS ctc_tutors (
tid int(10) NOT NULL,
  `name` varchar(64) NOT NULL,
  email varchar(64) NOT NULL,
  courses varchar(1024) NOT NULL
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=2 ;


ALTER TABLE ctc_applications
 ADD PRIMARY KEY (aid);

ALTER TABLE ctc_courses
 ADD PRIMARY KEY (cid);

ALTER TABLE ctc_tutors
 ADD PRIMARY KEY (tid);


ALTER TABLE ctc_applications
MODIFY aid int(10) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=2;
ALTER TABLE ctc_courses
MODIFY cid int(10) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=4;
ALTER TABLE ctc_tutors
MODIFY tid int(10) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=2;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
